#!/bin/sh

CC=gcc
CFLAGS="-Wall -W -O2 -march=native -pipe"
LDFLAGS="-lm"
SRC_DIR=sa
OUTPUT=bin/sony-acpid
OUTPUTDIR=$(dirname $OUTPUT)

if [ ! -d $OUTPUTDIR ]; then
	mkdir $OUTPUTDIR
fi

$CC $CFLAGS $LDFLAGS -o $OUTPUT $SRC_DIR/*.c
